### ISSUE TITLE
This program cannot change summary sheet

### ISSUE THREAD

**Issue by jucky154** [jucky154/hscontest#1]
このプログラムでは高校コンテストを対応していますが、スタート時には以下のように正しく計算できません。
![start](https://user-images.githubusercontent.com/58735989/119772149-b2278280-bef9-11eb-952b-eb27937c7430.png)
交信データの編集や追加を行うと正しく計算されます。
![edit](https://user-images.githubusercontent.com/58735989/119772210-c8354300-bef9-11eb-9237-c523a867f5c0.png)
また、サマリーについては計算が反映されていません。
![elog](https://user-images.githubusercontent.com/58735989/119772269-db481300-bef9-11eb-80f5-a29fce3adfd5.png)

正しいかどうかの判定は公式サイトのpdfの交信データを参照しました
![model](https://user-images.githubusercontent.com/58735989/119772318-ec911f80-bef9-11eb-8439-b90a250b279c.png)

**Comment by JG1VPP** [comment]
これはコンテストを開くときにzinsert関数は呼び出されるがzverify関数が呼び出されないためだと思います。
zLog側を修正します。

**Comment by jucky154** [comment]
サマリーについては点数がscore windowで正しい際も計算できていません。

**Comment by jucky154** [comment]
![elog1](https://user-images.githubusercontent.com/58735989/119793592-b069b900-bf11-11eb-9fa7-1f8c8277102b.png)
elogの場合ですが、mul2に入れたはずのHS or Cも表示されません
（これはscore windowでは正しく計算されているときに出力したものです）

**Comment by JG1VPP** [comment]
サマリーシートとはJARL R2.0のことですか？

**Comment by JG1VPP** [comment]
JARL R1.0の場合、得点は反映されません。仕様です。

**Comment by JG1VPP** [comment]
サマリーシートR1.0についてもDLLで総得点を計算するようにします。

**Comment by jucky154** [comment]
サマリーシートR2.0は問題ありませんでした。他の保存形式は得点などを記述しないので問題ないと思います。
