### ISSUE TITLE
Second Multi is not worked when past log is open

### ISSUE THREAD

**Issue by jucky154** [jucky154/hscontest#2]
This DLL calculates the second multi when the zLog calls insert or delete. When past log is open, the zLog calls only verify. Therefore, it cannot calculate score.

**Comment by JG1VPP** [comment]
To clarify that the insert and delete events are caused by the user's logging operation, those functions are no longer called when the file is opened.
Please read the ZLO file by yourself and calculate initial score.
DLL can access the ZLO file path by `Query('{F}')`.
I'll prepare a function to read the ZLO file.

**Comment by JG1VPP** [comment]
Could you please use LoadBinaryData function as follows:

```
func onAssignEvent(contest, configs string) {
  binary_data, err := os.ReadFile(Query("{F}"))
  if err != nil {
    initial_qsos := binary_data.LoadBinaryData()
  }
```

https://nextzlog.github.io/zylo/#func-binarydata-loadbinarydata

**Comment by jucky154** [comment]
```
func onAssignEvent(contest, configs string) {
 	var binary_data BinaryData
 	binary_data, err := os.ReadFile(Query("{F}"))
 	if err == nil {
 		initial_qsos := binary_data.LoadBinaryData()
		for _,qso_data := range initial_qsos{
 			if qso_data.GetMul2() == "HS"{
				hsmults = hsmults +1
			}
 		}		
 	}
}

```
does not work

**Comment by JG1VPP** [comment]
Sorry, I corrected the function.
Could you please try `LoadZLO`?
https://nextzlog.github.io/zylo/#func--loadzlo

**Comment by jucky154** [comment]
I tried to use LoadZLO. However, zbuild loaded old version zylo.(I have already deleted utils.go, .sum and .mod) Therefore, I cannot use LoadZLO.

**Comment by JG1VPP** [comment]
Did you download the latest zbuild?
zutils.go is bundled inside zbuild, so you should use the latest zbuild.

**Comment by jucky154** [comment]
Yes.
I downloaded the latest zbuild form https://github.com/nextzlog/zylo/releases 10 minutes ago.
I think that the latest zbuild did not reflect the latest code.

**Comment by JG1VPP** [comment]
I downloaded zbuild now and found zutils.go in the working directory after ran zbuild.
There was no problem.

**Comment by jucky154** [comment]
Thank you. I downloaded zbuild now and found the latest zutils.go.

**Comment by jucky154** [comment]
```
func onAssignEvent(contest, configs string) {
	var binary_data BinaryData
	binary_data, err := os.ReadFile(Query("{F}"))
	if err == nil {
		initial_qsos := LoadZLO(binary_data)
   	for _,qso_data := range initial_qsos{
			if qso_data.GetMul2() == "HS"{
   			hsmults = hsmults +1
   		        }
		}		
	}
}
```
doesn't work.
Could you tell me how to disconnect []QSO ?

**Comment by JG1VPP** [comment]
Could you please tell me the situation in detail?

**Comment by jucky154** [comment]
I sent you the detail data by slack because the pictures have a lot of my PC data.

**Comment by JG1VPP** [comment]
I see.
I corrected that function again.
Sorry for annoying you.
Could you please try again using the latest zlog release and zbuild?

**Comment by jucky154** [comment]
Thanks.

Now, when zlog open the binary file, zlog cannot calculate the score correctly.
However, when the binary is edited(ex. insert/delele/edit), zlog shows  correct score.
Probably, zlog calls onPointevent before onassignevent finishes its job.

(before edit)
![before-edit](https://user-images.githubusercontent.com/58735989/132134263-d56cbef8-4387-46f0-a1ca-e226f21d69ef.png)

(after edit)
![after-edit](https://user-images.githubusercontent.com/58735989/132134260-8a408256-9a19-48a4-aeee-dfa63584efca.png)

**Comment by JG1VPP** [comment]
Did this problem occur before zLog v2.7.0.2z2?

**Comment by jucky154** [comment]
No.
I used zLog v2.7.0.2z10.
(I downloaded the zlog and used, yesterday.)

**Comment by JG1VPP** [comment]
I think this problem has been around since before, but I found the cause and I'll fix it.

**Comment by JG1VPP** [comment]
Could you please use zLog v2.7.0.2z11?

**Comment by jucky154** [comment]
Thank you very much.
The DLL work correctly. Therefore, High school contest DLL can be released.
